### ISSUE TITLE
LineHeight attributes lost when text is set to empty

### ISSUE THREAD

**Issue by vol24pl** [Geri-Borbas/iOS.Blog.UILabel_Typography_Extensions#1]
`lineHeight` should work even when the text is setup after the `lineHeight`

STEPS TO REPRODUCE.
1. Move ` .with(text: text),` AFTER setting up the the line height in `LineHeightViewController`
```swift
UILabel()
    .with {
        $0.textColor = .label
        $0.font = UIFont.newYork(ofSize: 1024 / 26.0 / 2.0)
        $0.lineHeight = 50
        $0.numberOfLines = 0
        $0.showGrid = true
        $0.underline = .single
        self.label = $0
    }
    .with(text: text),

```

Expected:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/7266741/127011823-10c38bd4-bd63-40df-9fb6-8dabd5019a92.png">

Result:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/7266741/127011677-2481deb1-fb28-4a7c-a361-70a357ae13d4.png">

**Comment by vol24pl** [comment]
You can also just change to
`$0.titleLabel?.letterSpacing = 500`
in `withButtonStyle` to see that setting up text after style does not work properly.

If you swap order to 
```swift
.withButtonStyle
    .with {
    $0.addTarget(target, action: selector, for: .touchUpInside)
    $0.setTitle(title, for: .normal) //letter spacing AFTER text
}
```
You will see it's working as intended.

===

Underlying problem is that AttributedText with empty string simply does not store anything you set up.

if the text is `""`, `addAttribute(.baselineOffset, value: baselineOffset)` does not do anything.

**Comment by Geri-Borbas** [comment]
Makes sense. After all, it is (now) an attributed string extension. If no text, then there is no attributed text to store attributes on.

> Earlier there were designs where I stored the attributes in a separate storage, so they get applied regardless of the label content, but honestly I did not like the overhead coming with duplicate everything attributed text already implemented. See history around [commit 0.6.2](https://github.com/Geri-Borbas/iOS.Blog.UILabel_Typography_Extensions/tree/9793eb6a43e23e657fd1c291fac049b3aa38dab1/UILabel_Typography_Extensions/Typography).

**Comment by Geri-Borbas** [comment]
Makes sense. After all, it is (now) **an attributed string extension**. If no text, then there is no attributed text to store attributes on.

Earlier on, there were designs where I **stored the attributes in a separate storage** (see [`UILabel+DeprecatedExtensions.swift`](https://github.com/Geri-Borbas/iOS.Blog.UILabel_Typography_Extensions/blob/main/UILabel_Typography_Extensions/Typography/Drafts/UILabel+DeprecatedExtensions.swift), so they get applied regardless of the label content, but honestly I did not like the overhead coming with duplicating everything that attributed text already implemented.

However, if you think it makes more sense for your use-case, you may use that (or something built on that) as well. 

Alternatively, you may hack the `text` setter to set a thin white space character (https://en.wikipedia.org/wiki/Whitespace_character) instead of `nil` out the attributed string.

**Comment by vol24pl** [comment]
I've used the whitespace but it felt like a hack, as `.isEmpty` wont work, etc.

I've created a solution that stores the attributes when string is empty, and swaps it once the string contains anything. Do you want me to create a pull request to see it? Not a lot of overhead. About `+30 / - 16` LoC change
